config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :artifacts

  root to: 'artifacts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artifact.rb
class Artifact < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  mount_uploader :file, ArtifactUploader

  belongs_to :creator, class_name: "User"

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :es_file, type: 'attachment', fields: {
          name:          { store: true },
          content:       { store: true, term_vector: "with_positions_offsets" },
          title:         { store: true },
          date:          { store: true },
        }
      indexes :filename
      indexes :description
    end
  end

  def filename
    fn = super

    if fn.present?
      fn
    else
      file_identifier
    end
  end

  def es_file
    if file.present?
      Base64.encode64 File.read file.path
    else
      ""
    end
  end

  def as_indexed_json options = {}
    as_json only: [:id, :description], methods: [:es_file, :filename]
  end

  def self.search term
    return all unless term.present?
    a = __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: term,
            fields: ["es_file.content", "filename", "description"]
          }
        },
        highlight: {
          pre_tags: ['<em class="search-highlight">'],
          post_tags: ['</em>'],
          fields: {
            "es_file.content": {},
            filename: { number_of_fragments: 0 },
            description: {}
          }
        }
      }
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:search]
      @results = Artifact.search params[:search]
      @artifacts = @results.records
    else
      @results = []
      @artifacts = Artifact.all
    end
  end

  def show
    @artifact = Artifact.find params[:id]

    send_file @artifact.file.path
  end

  def new
    @artifact = Artifact.new
  end

  def create
    @artifact = Artifact.new artifact_params.merge creator: current_user

    if @artifact.save
      redirect_to artifacts_path, notice: t('artifacts.created')
    else
      render :new
    end
  end

  def edit
    @artifact = Artifact.find params[:id]
  end

  def update
    @artifact = Artifact.find params[:id]

    if @artifact.update artifact_params
      redirect_to artifacts_path,
        notice: t('artifacts.updated', artifact: @artifact.filename)
    else
      render :edit
    end
  end

  def destroy
    @artifact = Artifact.find params[:id]

    if @artifact.destroy
      redirect_to artifacts_path,
        notice: t('artifacts.destroyed', artifact: @artifact.filename)
    else
      redirect_to artifact_path(@artifact),
        alert: t('artifacts.error_destroying')
    end
  end

private
  def artifact_params
    params.require(:artifact).permit(
      :file,
      :file_cache,
      :filename,
      :description
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artifacts/_form.html.erb
<% if @artifact.persisted? %>
  <div class="row">
    <div class="col-sm-12">
      <%= link_to "Delete", artifact_path(@artifact), method: :delete, data: { confirm: "Are you sure you want to delete this artifact?" }, class: 'btn btn-danger pull-right' %>
    </div>
  </div><br>
<% end %>

<%= form_for @artifact, html: { class: 'form-horizontal' } do |f| %>
  <% if @artifact.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@artifact.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @artifact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% unless @artifact.persisted? %>
    <div class="form-group">
      <%= f.label :file, nil, class: 'col-sm-2' %>
      <div class="col-sm-10">
        <%= f.file_field :file, class: 'form-control' %>
        <%= f.hidden_field :file_cache %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :filename, nil, class: 'col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :filename, placeholder: "Optionally give the file a custom name", class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, nil, class: 'col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_area :description, placeholder: "What's it about? Who's in it?", class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to "Back", artifacts_path, class: 'btn btn-default pull-right' %>
    </div>
  </div>
<% end %>

app/views/artifacts/edit.html.erb
<h2>Edit artifact</h2><br>

<%= render 'form'  %>

app/views/artifacts/index.html.erb
<%= link_to "Upload", new_artifact_path, class: 'btn btn-default pull-right' %>

<%= form_tag artifacts_path, method: :get, class: 'form-inline' do %>
  <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Search" %>
  <%= submit_tag "Search", class: 'btn btn-default' %>
  <%= link_to("Clear search", artifacts_path) if params[:search].present? %>
<% end %>

<br>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Uploaded by</th>
      <th>Uploaded at</th>
      <% if current_user %>
        <% cols = 5 %>
        <th></th>
      <% else %>
        <% cols = 4 %>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @artifacts.each do |artifact| %>
      <% result = @results.find{ |r| r.id.to_i == artifact.id } %>
      <tr>
        <td>
          <% if result && result.highlight.key?('filename') %>
            <%= link_to result.highlight['filename'].first.html_safe, artifact %>
          <% else %>
            <%= link_to artifact.filename, artifact %>
          <% end %>
        </td>
        <td><%= artifact.file.size.fdiv(1024).fdiv(1024).round(2) %> MB</td>
        <td><%= artifact.creator.email %></td>
        <td><%= artifact.created_at %></td>
        <% if current_user %>
          <td><%= link_to "edit", edit_artifact_path(artifact) %></td>
        <% end %>
      </tr>
      <% if result && result.highlight.key?('es_file.content') %>
        <tr class="search-result-blurb">
          <td colspan="<%= cols %>">
            <h5>Content:</h5>
            <% result.highlight['es_file.content'].each do |snippet| %>
              <p><%= snippet.html_safe %> ...</p>
            <% end %>
          </td>
        </tr>
      <% end %>
      <% if result && result.highlight.key?('description') %>
        <tr class="search-result-blurb">
          <td colspan="<%= cols %>">
            <h5>Description:</h5>
            <% result.highlight['description'].each do |snippet| %>
              <p><%= snippet.html_safe %> ...</p>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/artifacts/new.html.erb
<h2>New artifact</h2><br>

<%= render 'form'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ALHG</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <h1>ALHG Archive</h1><br>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>